#!/bin/bash

# fetch dogecoin src if it doesn't exist:
if [ ! -d "dogecoin" ]; then
    # adjust docker/github repo/branch as needed:
    git clone https://github.com/xanimo/dogecoin
    pushd /dogecoin
        git checkout 1.14.7-dev-depends
    popd
fi

docker buildx build -t xanimo/dogecoin:darwin . \
--load 2> $PWD/build-log.txt | sleep 2 | tail -f $PWD/build-log.txt