#!/bin/bash
export LC_ALL=C
set -e -o pipefail

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

config_env() {
    case "$TARGET_HOST_TRIPLET" in
        "arm-linux-gnueabihf")
            OS=linux
            TARGET_ARCH="arm32v7"
        ;;
        "aarch64-linux-gnu")
            OS=linux
            TARGET_ARCH="arm64v8"
        ;;
        "x86_64-pc-linux-gnu")
            OS=linux
            TARGET_ARCH="amd64"
        ;;
        "i686-pc-linux-gnu")
            OS=linux
            TARGET_ARCH="amd64"
        ;;
        "x86_64-w64-mingw32")
            OS=linux
            TARGET_ARCH="amd64"
        ;;
        "i686-w64-mingw32")
            OS=linux
            TARGET_ARCH="amd64"
        ;;
        "x86_64-apple-darwin11")
            OS=linux
            TARGET_ARCH="amd64"
        ;;
        "all")
            ALL_HOST_TRIPLETS=("x86_64-pc-linux-gnu" "i686-pc-linux-gnu" "aarch64-linux-gnu" "arm-linux-gnueabihf" "x86_64-w64-mingw32" "i686-w64-mingw32" "x86_64-apple-darwin11")
        ;;
        *)
            ERROR=1
        ;;
    esac
}

URL="https://github.com/xanimo/dogecoin"
CURRENT_URL=$(git config --get remote.origin.url)
COMMIT="1.14.7-dev"
ALL_HOST_TRIPLETS=""
TARGET_HOST_TRIPLET=""
for i in "$@"
do
case $i in
    -c=*|--commit=*)
        COMMIT="${i#*=}"
    ;;
    -h=*|--host=*)
        HOST="${i#*=}"
        TARGET_HOST_TRIPLET=($HOST)
        config_env
    ;;
    -u=*|--url=*)
        URL="${i#*=}"
    ;;
    *)
        ERROR=1
    ;;
esac
done

if [ "$ERROR" ]; then
    echo "Please provide a host to build and try again."
    exit $ERROR
fi

# fetch dogecoin src if it doesn't exist:
if [ ! -d "dogecoin" ]; then
    # adjust docker/github repo/branch as needed:
    git clone $URL
    pushd /dogecoin
        git checkout $COMMIT
        if [ ! -d "depends/SDKs" ]; then
            wget https://gist.githubusercontent.com/xanimo/7b3ae8f43e3b8b3834e7e281dc263de2/raw/22c72d80ce1d8e5710a9a2d1edaa8efe2c6f621d/macos-sdk.sh
            chmod +x macos-sdk.sh
            ./macos-sdk.sh
            rm macos-sdk.sh
        fi
    popd
else
    pushd /dogecoin
        re="^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+)(.git)*$"
        if [[ $CURRENT_URL =~ $re ]]; then
            protocol=${BASH_REMATCH[1]}
            separator=${BASH_REMATCH[2]}
            hostname=${BASH_REMATCH[3]}
            user=${BASH_REMATCH[4]}
            repo=${BASH_REMATCH[5]}
        fi
        if [[ $URL != "https://github.com/$user/dogecoin" ]]; then
            git remote add $user $URL
            git fetch $user
        fi
        if [[ $COMMIT != "1.14.7-dev" ]]; then
            git checkout $COMMIT
        fi
    popd
fi

build() {
    # there is no i386/ubuntu:focal image so we have to build on amd64 hence DPKG_ARCH
    docker buildx build \
    --build-arg FLAVOR=${FLAVOR:-"focal"} \
    --build-arg ARCH=$TARGET_ARCH \
    --build-arg TARGET_HOST=$TARGET_HOST_TRIPLET \
    -t xanimo/dogecoin:$TARGET_HOST_TRIPLET . --load \
    2> $PWD/$TARGET_HOST_TRIPLET-build-log.txt | sleep 2 | tail -f $PWD/$TARGET_HOST_TRIPLET-build-log.txt
}

if [[ "$ALL_HOST_TRIPLETS" != "" ]]; then
    END=$((${#ALL_HOST_TRIPLETS[@]} - 1))
    for i in "${!ALL_HOST_TRIPLETS[@]}"
    do
    :
        TARGET_HOST_TRIPLET="${ALL_HOST_TRIPLETS[$i]}"
        config_env
        build
    done
else
        config_env
        build 
fi
